name: Build and publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build images
        run: ./build_and_push.sh build
      - name: login to github
        run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: push images
        run: ./build_and_push.sh push
